language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
- PACKAGE="rwo-examples"
- PINS="rwo:https://github.com/realworldocaml/scripts.git#v2"
- DISTRO="ubuntu-16.04" OCAML_VERSION="4.04.2"
- OPAMJOBS=2
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: v2-sexp
  on:
    branch: v2
