language: c
sudo: false
services:
  - docker
branches:
  except:
  - gh-pages
install: scripts/install
script: scripts/build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/site
  github_token: $GITHUB_TOKEN
  on:
    branch: master
